In [1]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Iris.xls', 'k-nn.ipynb']


In [2]:
#import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#load dataset using pandas

df = pd.read_excel('Iris.xls')

In [4]:
df.head(10)

sepal length  sepal width  petal length  petal width         iris  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   
5           5.4          3.9           1.7          0.4  Iris-setosa   
6           4.6          3.4           1.4          0.3  Iris-setosa   
7           5.0          3.4           1.5          0.2  Iris-setosa   
8           4.4          2.9           1.4          0.2  Iris-setosa   
9           4.9          3.1           1.5          0.1  Iris-setosa   

   Unnamed: 5  Unnamed: 6      sepal length.1  Unnamed: 8  
0         NaN         NaN               Count  150.000000  
1         NaN         NaN             Minimum    4.300000  
2         NaN         NaN             Maximum    7.900000  
3         NaN         NaN                Mean    5.843333  
4         NaN         NaN              Median    5.800000  
5         NaN         NaN                Mode    5.000000  
6         NaN         NaN          Quartile 1    5.100000  
7         NaN         NaN               Range    3.600000  
8         NaN         NaN            Variance    0.685694  
9         NaN         NaN  Standard Deviation    0.828066

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 9 columns):
sepal length      150 non-null float64
sepal width       150 non-null float64
petal length      150 non-null float64
petal width       150 non-null float64
iris              150 non-null object
Unnamed: 5        0 non-null float64
Unnamed: 6        0 non-null float64
sepal length.1    13 non-null object
Unnamed: 8        13 non-null float64
dtypes: float64(7), object(2)
memory usage: 10.6+ KB


In [6]:
#check which all columns have null values

df.isnull().sum()

sepal length        0
sepal width         0
petal length        0
petal width         0
iris                0
Unnamed: 5        150
Unnamed: 6        150
sepal length.1    137
Unnamed: 8        137
dtype: int64

In [7]:
#As dependent and independent columns have 'zero' null values

In [8]:
#independent variable
X = df.iloc[ : , :4].values

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
X.shape

(150, 4)

In [11]:
#dependent variable
y = df.iloc[ : , 4].values

In [12]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [13]:
y.shape

(150,)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train ,X_test ,y_train ,y_test = train_test_split(X ,y ,test_size = 0.2)

In [16]:
X_train

array([[5.5, 2.6, 4.4, 1.2],
       [6.8, 2.8, 4.8, 1.4],
       [6.6, 3. , 4.4, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6.3, 2.5, 5. , 1.9],
       [5.1, 3.5, 1.4, 0.3],
       [5.5, 4.2, 1.4, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [6.7, 3. , 5. , 1.7],
       [7.9, 3.8, 6.4, 2. ],
       [5. , 3.5, 1.6, 0.6],
       [6.3, 3.4, 5.6, 2.4],
       [5.8, 2.8, 5.1, 2.4],
       [6.5, 2.8, 4.6, 1.5],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 4.4, 1.5, 0.4],
       [6.8, 3.2, 5.9, 2.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [6.8, 3. , 5.5, 2.1],
       [5.8, 2.7, 3.9, 1.2],
       [4.9, 3.1, 1.5, 0.1],
       [6. , 3.4, 4.5, 1.6],
       [5.6, 3. , 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [6.3, 2.5, 4.9, 1.5],
       [4.8, 3.4, 1.6, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.1, 3. , 4.9, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [6.5, 3

In [17]:
X_test

array([[7.6, 3. , 6.6, 2.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.5, 3. , 5.8, 2.2],
       [5.4, 3.9, 1.3, 0.4],
       [6.2, 2.8, 4.8, 1.8],
       [5. , 3.2, 1.2, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [7.4, 2.8, 6.1, 1.9],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 2.9, 4.3, 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [6.9, 3.1, 5.4, 2.1],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.4, 1.5, 0.4],
       [7.2, 3.6, 6.1, 2.5],
       [5. , 3.3, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [5.2, 3.4, 1.4, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [4.4, 2.9, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [7.7, 2.6, 6.9, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [5.5, 3.5, 1.3, 0.2]])

In [18]:
y_train

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-s

In [19]:
y_test

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa'], dtype=object)

In [20]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [21]:
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)

In [22]:
X_train

array([[-0.43693145, -1.06459972,  0.33647803, -0.04408316],
       [ 1.18595679, -0.59231889,  0.57575129,  0.22719785],
       [ 0.93628168, -0.12003805,  0.33647803,  0.22719785],
       [-0.81144412,  2.47750657, -1.39825314, -1.53612874],
       [ 0.56176901, -1.30074014,  0.69538792,  0.90540039],
       [-0.93628168,  1.06066405, -1.45807145, -1.26484773],
       [-0.43693145,  2.71364699, -1.45807145, -1.40048824],
       [ 0.06241878, -0.12003805,  0.75520624,  0.76975988],
       [ 1.06111923, -0.12003805,  0.69538792,  0.63411937],
       [ 2.55916991,  1.76908531,  1.53284435,  1.04104089],
       [-1.06111923,  1.06066405, -1.33843482, -0.85792621],
       [ 0.56176901,  0.82452363,  1.05429782,  1.58360292],
       [-0.06241878, -0.59231889,  0.75520624,  1.58360292],
       [ 0.81144412, -0.59231889,  0.45611466,  0.36283836],
       [ 1.06111923,  0.58838321,  1.11411614,  1.71924343],
       [-0.18725634,  3.18592783, -1.39825314, -1.12920722],
       [ 1.18595679,  0.

In [23]:
X_test

array([[ 2.18465724, -0.12003805,  1.65248098,  1.1766814 ],
       [-1.56046946,  0.82452363, -1.45807145, -1.26484773],
       [ 0.81144412, -0.12003805,  1.17393445,  1.31232191],
       [-0.56176901,  2.00522573, -1.51788977, -1.12920722],
       [ 0.43693145, -0.59231889,  0.57575129,  0.76975988],
       [-1.06111923,  0.35224279, -1.57770809, -1.40048824],
       [-0.18725634, -1.30074014,  0.69538792,  1.04104089],
       [ 1.93498213, -0.59231889,  1.3533894 ,  0.90540039],
       [-0.18725634,  1.76908531, -1.27861651, -1.26484773],
       [-1.06111923,  0.82452363, -1.39825314, -1.40048824],
       [ 0.31209389, -1.06459972,  1.05429782,  0.22719785],
       [ 0.68660656, -0.35617847,  0.27665971,  0.09155734],
       [-0.56176901,  2.00522573, -1.27861651, -1.12920722],
       [ 1.31079435,  0.11610237,  0.93466119,  1.1766814 ],
       [-1.18595679,  0.11610237, -1.39825314, -1.53612874],
       [-0.56176901,  0.82452363, -1.39825314, -1.12920722],
       [ 1.68530702,  1.

In [24]:
y_train

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-s

In [25]:
y_test

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa'], dtype=object)

In [26]:
#knn algorithm 
from sklearn.neighbors import KNeighborsClassifier

In [27]:
classifier = KNeighborsClassifier(n_neighbors=5 , p=2, metric='minkowski')
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [28]:
predictions = classifier.predict(X_test)

In [29]:
predictions

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa'], dtype=object)

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [31]:
confusion_matrix(y_test,predictions)

array([[14,  0,  0],
       [ 0,  4,  0],
       [ 0,  1, 11]], dtype=int64)

In [32]:
accuracy_score(y_test,predictions) *100

96.66666666666667